package com.medtroniclabs.spice.ui.medicalreview.utils

import com.medtroniclabs.spice.data.history.Investigation

object MedicalReviewDefinedParams {
    const val PC_ITEM = "PresentingComplaintsType"
    const val SE_ITEM = "SystemicExaminationsType"
    const val CLINICAL_NOTES = "ClinicalNotes"
    const val GENERAL_SE_ITEM="GeneralExaminationsType"
    const val MEMBER_REG="MemberReg"
    const val Notes = "Notes"
    const val CHIP_ITEMS = "ChipItems"
    const val MEDICAL_REVIEW_ADD_MEMBER = "MedicalReviewAdd"
    const val PC_5YEARS = ">5Y"
    const val MOTHER_VITAMIN_TAG = "motherVitaminSelection"
    const val BREAST_FEEDING_TAG = "breastFeedingTag"
    const val EXCLUSIVE_BREAST_FEED_TAG = "exclusiveBreastFeedTag"
    const val SUMMARY_ITEM = "SummaryItem"
    const val NOT_ALIVE="NotAlive"
    const val Albendazole = "Albendazole"
    const val HH_RELATIONSHIP= "household_head_relationship"
    const val GESTATIONAL_AGE = "gestationalAge"
    const val FreshStillBirth = "freshStillBirth"
    const val MaceratedStillBirth="maceratedStillBirth"
    const val StillBirth = "stillBirth"
    const val Miscarriage="miscarriage"
    const val LiveBirth="liveBirth"
    const val CF_ITEM = "ComorbiditiesFragment"
    const val respiratory = "respiratory"
    const val PHUFlow="PHUFlow"

    const val CONTRACEPTIVES_ITEMS = "ContraceptivesItems"
    const val CONTRACEPTIVES_VALUES = "ContraceptivesValues"
    const val ClientType = "clientType"
    const val PostPartum = "PostPartum"
    const val CombineOralContraceptive = "CombinedOralContraceptive"
    const val ProgestinOnlyOrals= "Progestin Only Orals"
    const val Microlut = "Microlut"
    const val Injectables = "Injectables"
    const val Implants = "Implants"
    const val Condoms = "Condoms"
    const val EmergencyContraceptive = "Emergency contraceptive"
    const val PermanentMethod = "Permanent Method"

    const val HIV_ELIGIBILITY_ITEM = "HivEligibility"
    const val HIV_ELIGIBILITY_VALUES = "HivEligibilityValues"
    const val HaveYouTakenHivTestBefore = "HaveYouTakenHivTestBefore"
    const val HIV_TEST_ITEM = "HivTest"
    const val HIV_TEST_VALUES = "HivTestValues"
    const val A1_TEST_RESULT = "A1TestResult"
    const val A2_TEST_RESULT = "A2TestResult"
    const val A3_TEST_RESULT = "A3TestResult"
    const val OtherInjectableComments = "OtherInjectableComments"
    const val OtherImplantComments = "OtherImplantComments"
    const val OtherPermanentMethodComments = "OtherPermanentMethodComments"
    const val OtherProgestinOnlyOralsComments = "OtherProgestinOnlyOralsComments"
    const val CombinedOralContraceptiveComments = "CombinedOralContraceptiveComments"
    const val MicrolutQuantity = "MicrolutQuantity"
    const val OtherOralSpecify = "OtherOralSpecify"
    const val OtherSpecify = "OtherSpecify"
    const val OtherInjectablesSpecify = "OtherInjectablesSpecify"
    const val OtherImplantSpecify = "OtherImplantSpecify"
    const val OtherFPMethod = "OtherFPmethod"
    const val EMTCCT_VISIT_STATUS = "emtctVisitStatus"
    const val HBsAg = "HBsAg"
    const val HIV_SYPHILIS_DUO_TEST = "SyphilisDuoTest"
    const val startDate = "startDate"
    const val endDate = "endDate"
    const val HIV_STATUS = "HIV_STATUS_FRAGMENT"
    const val tbPreventiveDateRange = "tbPreventiveDateRange"
    const val cotrimoxazoleDateRange = "cotrimoxazoleDateRange"
    const val tbTreatmentDateRange = "tbTreatmentDateRange"
    const val cryptococcalMeningitisDateRange = "cryptococcalMeningitisDateRange"

    const val Investigation = "Investigation"
    const val PRESCRIPTION = "Prescription"

    const val cd4_percentage= "cd4Percentage"
    const val isViralLoadTestRecommended= "isViralLoadTestRecommended"
    const val notEstablished= "notEstablished"
    const val emtctVisitStatus = "emtctVisitStatus"
}