package com.medtroniclabs.spice.ui.medicalreview.utils

object MedicalReviewDefinedParams {
    const val PC_ITEM = "PresentingComplaintsType"
    const val SE_ITEM = "SystemicExaminationsType"
    const val CLINICAL_NOTES = "ClinicalNotes"
    const val GENERAL_SE_ITEM="GeneralExaminationsType"
    const val MEMBER_REG="MemberReg"
    const val Notes = "Notes"
    const val CHIP_ITEMS = "ChipItems"
    const val MEDICAL_REVIEW_ADD_MEMBER = "MedicalReviewAdd"
    const val PC_5YEARS = ">5Y"
    const val MOTHER_VITAMIN_TAG = "motherVitaminSelection"
    const val BREAST_FEEDING_TAG = "breastFeedingTag"
    const val EXCLUSIVE_BREAST_FEED_TAG = "exclusiveBreastFeedTag"
    const val SUMMARY_ITEM = "SummaryItem"
    const val NOT_ALIVE="NotAlive"
    const val Albendazole = "Albendazole"
    const val HH_RELATIONSHIP= "household_head_relationship"
    const val GESTATIONAL_AGE = "gestationalAge"
    const val FreshStillBirth = "freshStillBirth"
    const val MaceratedStillBirth="maceratedStillBirth"
    const val StillBirth = "stillBirth"
    const val Miscarriage="miscarriage"
    const val LiveBirth="liveBirth"
    const val CF_ITEM = "ComorbiditiesFragment"
    const val respiratory = "respiratory"
    const val PHUFlow="PHUFlow"

    const val CONTRACEPTIVES_ITEMS = "ContraceptivesItems"
    const val CONTRACEPTIVES_VALUES = "ContraceptivesValues"
    const val ClientType = "clientType"
    const val PostPartum = "PostPartum"
    const val CombineOralContraceptive = "CombinedOralContraceptive"
    const val ProgestinOnlyOrals= "Progestin Only Orals"
    const val Microlut = "Microlut"
    const val Injectables = "Injectables"
    const val Implants = "Implants"
    const val Condoms = "Condoms"
    const val EmergencyContraceptive = "Emergency contraceptive"
    const val PermanentMethod = "Permanent Method"
}