package com.medtroniclabs.spice.formgeneration.model

import com.medtroniclabs.spice.data.model.RecommendedDosageListModel

data class FormLayout(
    override val viewType: String,
    override val id: String,
    override val title: String,
    var family: String? = null,
    var visibility: String?,
    var prefixText: String? = null,
    var isMandatory: Boolean = false,
    var maxLength: Int? = null,
    var minLength: Int? = null,
    var blockedCharacterSet: String? = null,
    var inputType: Int? = null,
    var orientation: Int? = null,
    var errorMessage: String? = null,
    var cultureErrorMessage: String? = null,
    var disableFutureDate: Boolean? = null,
    var valueKeyNotNeeded: Boolean? = null,
    var minDate: Long? = null,
    var maxDate: Long? = null,
    var optionsList: ArrayList<Map<String, Any>>?,
    var dayOptionsList: ArrayList<Map<String, Any>>? = null,
    var timeOptionsList: ArrayList<Map<String, Any>>? = null,
    var isEnabled: Boolean? = null,
    var defaultValue: String? = null,
    var condition: ArrayList<ConditionalModel>? = null,
    var action: String? = null,
    var hint: String? = null,
    var isNeedAction: Boolean = false,
    var actionTitle: String? = null,
    var instructions: ArrayList<String>? = null,
    var instructionsCulture: ArrayList<String>? = null,
    var isSummary: Boolean? = null,
    var maxLines: Int? = null,
    var minValue: Double? = null,
    var minValueForHour: Int? = null,
    var minValueForMinute: Int? = null,
    var maxValue: Double? = null,
    var maxValueForHour: Int?=null,
    var maxValueForMinute: Int?=null,
    var pulseMinValue: Double? = null,
    var pulseMaxValue: Double? = null,
    var totalCount: Int? = null,
    var contentLength: Int? = null,
    var localDataCache: String? = null,
    var dependentID: String? = null,
    var unitMeasurement: String? = null,
    var isEditable: Boolean = false,
    var isCustomWorkflow: Boolean = false,
    var customWorkflowId: String? = null,
    var startValue: Double? = null,
    var endValue: Double? = null,
    var interval: Double? = null,
    var isAboveUpperLimit: Boolean = false,
    var optionType: String? = null,
    var mandatoryCount: Int? = null,
    var titleCulture: String? = null,
    var hintCulture: String? = null,
    var disableSpinner: Boolean? = null,
    var startsWith: ArrayList<String>? = null,
    var isEnrollment: Boolean? = true,
    var isReferred: Boolean? = null,
    var onlyAlphabets: Boolean? = null,
    var applyDecimalFilter: Boolean? = null,
    var backgroundColor: String? = null,
    var information: String? = null,
    var titleSummary: String? = null,
    var noOfDays: Int? = null,
    var informationVisibility: String? = null,
    var isBooleanAnswer: Boolean = false,
    var isInfo: String? = null,
    var dosageListItems: ArrayList<RecommendedDosageListModel>? = null,
    var maxDecimalPlaces: Int? = null,
    var menstrualPeriod: Boolean = false,
    var minDays: Int? = null,
    var maxDays: Int? = null,
    var unitList: ArrayList<Map<String, Any>>? = null,
    var maxAge: Int? = null,
    var code: String? = null,
    var url: String? = null,
    var resource: String? = null,
    var spinnerAsObject: Boolean = false,
    var ranges: ArrayList<RangeModel>? = null,
    var category: List<String>? = null,
    var textLabelColor: String? = null,
    var textLabelStyle: String? = null,
    var familyOrder: Int? = null,
    var ageCondition: ArrayList<String>? = null,
    var workflowType: ArrayList<String>? = null,
    var orderId: Int? = null
) : BaseViewParams

data class RangeModel(
    val unitType: String,
    val gender: String,
    val minRange: Double,
    val maxRange: Double,
    val displayRange: String
)

data class FormResponse(
    var formLayout: List<FormLayout>, var time: Long
)
data class BPModel(
    var systolic: Double? = null,
    var diastolic: Double? = null,
    var pulse: Double? = null,
)