package com.medtroniclabs.spice.model

import com.google.gson.annotations.SerializedName
import com.medtroniclabs.spice.data.history.DiseaseInfo

data class PatientListRespModel(
    val id: String? = null,
    val enrolmentId: String? = null,
    val enrollmentAt: String? = null,
    val name: String? = null,
    val firstName: String? = null,
    val lastName: String? = null,
    val middleName: String? = null,
    val programId: String? = null,
    val cvdRiskLevel: String? = null,
    val cvdRiskScore: Double? = null,
    val bmi: Double? = null,
    val gender: String? = null,
    val age: Int? = null,
    val birthDate: String? = null,
    val patientId: String? = null,
    val village: String? = null,
    val nationalID: Long? = null,
    val phoneNumber: String? = null,
    val memberId: String? = null,
    val neonateMemberId: String? = null,
    val occupation:String? =null,
    val landmark:String? = null,
    val fhirUrl: String? = null,
    val performer: String? = null,
    val chwName: String? = null,
    val houseHoldId: String? = null,
    val houseHoldNumber: Long? = null,
    val dateOfOnset:String? = null,
    var isPregnant: Boolean? = null,
    var isPregnancyRisk: Boolean? = null,
    var riskPatient: Boolean = false,
    @SerializedName("redRiskPatient")
    var isRedRiskPatient: Boolean = false,
    var riskColor: String? = null,
    val pregnancyDetails: PregnancyDetails? = null,
    val prescribedDetails : PrescribedDetails? = null,
    val villageId:String? = null,
    val relationship:String? = null,
    val phoneNumberCategory:String? = null,
    val diagnosis: List<DiseaseInfo>? = null,
    val pregnancyStatus: String? = null,
    val isRegularSmoker: Boolean? = null,
    val initialReviewed: Boolean? = false,
    val identityValue: String? = null,
    val isConfirmDiagnosis: Boolean = false,
    val height: Double? = null,
    val weight: Double? = null,
    val identityType: String? = null,
    val avgBloodPressure: String? = null,
    val glucoseUnit: String? = null,
    val glucoseValue: String? = null,
    val isPhq9: Boolean? = false,
    val isGad7: Boolean? = false,
    val mentalHealthLevels: List<String>? = null,
    val dateOfBirth: String? = null,
    val patientReference : String? =null,
    val encounterId : String? = null
)

data class PregnancyDetails(
    val lastMenstrualPeriod: String? = null,
    val ancVisitAssessment: Long? = null,
    val pncVisitAssessment: Long? = null,
    val childHoodVisitAssessment: Long? = null,
    val ancVisitMedicalReview: Int? = null,
    val pncVisitMedicalReview: Int? = null,
    val childHoodVisitMedicalReview: Long? = null,
    val patientStatus: String? = null,
    val height: Double? = null,
    val pulse: Double? = null,
    val estimatedDeliveryDate: String? = null,
    val gestationalAge: String? = null,
    val noOfFetus: Int? = null,
    val gravida: Int? = null,
    val neonatePatientId:String? = null,
    val parity: Int? = null,
    val patientBloodGroup: String? = null,
    val bmi: Double? = null,
    val pregnant: Boolean? = null,
    val ancVisit:String? = null,
    val villageId: String? = null,
    val dateOfDelivery:String?=null
)
data class SearchAndListResponse(
    val patientList: List<PatientListRespModel> = emptyList(),
    val referencePatientId: String? = null,
    val totalCount: Int? = null
)

data class PrescribedDetails(
    var firstName: String? = null,
    var lastName: String? = null,
    var phoneNumber: String? = null,
    var countryCode: String? = null,
    var createdAt: String? = null,
    var updatedAt: String? = null,
    var lastRefillDate: String? = null,
    var lastRefillVisitId: String? = null
)