# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

desc "Submit a new dev Build to firebase"
     lane :fireInternal do
     gradle(task: "clean assemble",build_type: "staging" )
     firebase_app_distribution(
          app: "1:791794371431:android:7a2a8380609de61d247dc2",
          firebase_cli_token:"1//0g-ubz1wdEX-PCgYIARAAGBASNgF-L9IrhmA36Ph_Q2GsqM0iBncWG-1GxUatwrJZ9kmgx-5LVJtzMBY3TYisMHTy5gBU90UXKA",
          testers: "hariharan@ideas2it.com,suganth.sakthivel@ideas2it.com,parthasarathy.elumalai@ideas2it.com,vijayakumar@ideas2it.com",
          release_notes: "Spice-SL Mobile Development Build"
      )
  end


  desc "Submit a new dev Build to firebase"
     lane :fireStaging do
     gradle(task: "clean assemble",build_type: "staging" )
     firebase_app_distribution(
          app: "1:791794371431:android:7a2a8380609de61d247dc2",
          firebase_cli_token:"1//0g-ubz1wdEX-PCgYIARAAGBASNgF-L9IrhmA36Ph_Q2GsqM0iBncWG-1GxUatwrJZ9kmgx-5LVJtzMBY3TYisMHTy5gBU90UXKA",
          testers: "hariharan@ideas2it.com,suganth.sakthivel@ideas2it.com,narayanan.b@ideas2it.com,nithyanandakumar@ideas2it.com,saddamhussain.mohammed@ideas2it.com,praveenrajr@ideas2it.com,vijayakumar@ideas2it.com,parthasarathy.elumalai@ideas2it.com,mdt-build@ideas2it.com",
          release_notes: "Spice-SL Mobile Development Build"
      )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end


  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
