package com.medtroniclabs.spice.db.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Pregnancy details table entity
 *
 * @param id : Autogenerated id
 * @param householdMemberLocalId : Autogenerated id from household member table
 * @param patientId : Patient id of household member
 * @param householdMemberId : FHIR id of household member
 * @param pregnancyEpisodeId : Unique identifier for the pregnancy episode
 * @param lastMenstrualPeriod : Last menstrual period date
 * @param estimatedDeliveryDate : Estimated delivery date
 * @param pregnancyTest : Test result stored from pregnant women registration
 * @param gravida : Gravida stored from pregnant women registration
 * @param parity : Parity stored from pregnant women registration
 * @param numberOfLivingChildren : Number of living children stored from pregnant women registration
 * @param ageOfLastChild : Age of last child stored from pregnant women registration
 */
@Entity(
    tableName = EntitiesName.PREGNANCY_DETAIL,
    indices = [Index(value = ["pregnancyEpisodeId"], unique = true)],
)
data class PregnancyDetail(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    var householdMemberLocalId: Long,
    var patientId: String? = null,
    var householdMemberId: String? = null,
    var pregnancyEpisodeId: String? = null,
    var tbContactTraceStatus: Int? = null,
    // Pregnancy details
    var lastMenstrualPeriod: String? = null,
    var estimatedDeliveryDate: String? = null,
    var pregnancyTest: String? = null,
    var gravida: Int? = null,
    var parity: Int? = null,
    var numberOfLivingChildren: Int? = null,
    var ageOfLastChild: String? = null,
    // Anc Details
    var ancVisitNo: Long? = null,
    var previousPregnancyComplications: String? = null,
    var pregnantWomanExistingIllness: String? = null, // JSON string of list
    var pregnantWomanOnTreatment: String? = null, // JSON string of list
    var highRiskPregnantWoman: String? = null, // JSON string of list
    var gapsInAnc: String? = null, // JSON string of list
    // Pnc Detail
    var pncVisitNo: Long? = null,
    var pncIllness: String? = null,
    var highRiskMother: String? = null,
    var gapsInPnc: String? = null,
    // Pregnancy outcome
    var dateOfDelivery: String? = null,
    var anyComplicationsDuringDelivery: String? = null,
    var typeOfAbortion: String? = null,
    var noOfNeonates: Int? = null,
    var neonatePatientId: String? = null,
    var isDeliveryAtHome: Boolean? = null,
    var neonateHouseholdMemberLocalId: Long? = null,
    var isNeonateDeathRecordedByPHU: Boolean? = null,
    // Childhood Visit Detail
    var childVisitNo: Long? = null,
    var startAt: String? = null,
    var endAt: String? = null,
)
