package com.medtroniclabs.spice.db.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Pregnancy details table entity
 *
 * @param id : Autogenerated id
 * @param householdMemberLocalId : Autogenerated id from household member table
 * @param patientId : Patient id of household member
 * @param householdMemberId : FHIR id of household member
 * @param lastMenstrualPeriod : Last menstrual period date
 * @param estimatedDeliveryDate : Estimated delivery date
 * @param pregnancyTest : Test result stored from pregnant women registration
 * @param gravida : Gravida stored from pregnant women registration
 * @param parity : Parity stored from pregnant women registration
 * @param numberOfLivingChildren : Number of living children stored from pregnant women registration
 * @param ageOfLastChild : Age of last child stored from pregnant women registration
 */
@Entity(tableName = EntitiesName.PREGNANCY_DETAIL)
data class PregnancyDetail(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    var householdMemberLocalId: Long,
    var patientId: String? = null,
    var householdMemberId: String? = null,
    // Anc Details
    var ancVisitNo: Long? = null,
    var lastMenstrualPeriod: String? = null,
    var estimatedDeliveryDate: String? = null,
    // Pnc Detail
    var pncVisitNo: Long? = null,
    var dateOfDelivery: String? = null,
    var noOfNeonates: Int? = null,
    var neonatePatientId: String? = null,
    var isDeliveryAtHome: Boolean? = null,
    var neonateHouseholdMemberLocalId: Long? = null,
    var isNeonateDeathRecordedByPHU: Boolean? = null,
    // Childhood Visit Detail
    var childVisitNo: Long? = null,
    var tbContactTraceStatus: Int? = null,
    // Pregnancy details
    var pregnancyTest: String? = null,
    var gravida: Int? = null,
    var parity: Int? = null,
    var numberOfLivingChildren: Int? = null,
    var ageOfLastChild: String? = null,
)
