package com.medtroniclabs.spice.formgeneration.config

object ViewType {
    const val VIEW_TYPE_FORM_CARD_FAMILY = "CardView"
    const val VIEW_TYPE_FORM_EDITTEXT = "EditText"
    const val VIEW_TYPE_FORM_EDITTEXT_AREA = "EditTextArea"
    const val VIEW_TYPE_FORM_RADIOGROUP = "RadioGroup"
    const val VIEW_TYPE_FORM_DATEPICKER = "DatePicker"
    const val VIEW_TYPE_FORM_MULTISELECT_DATEPICKER = "MultiSelectDatePicker"
    const val VIEW_TYPE_FORM_SPINNER = "Spinner"
    const val VIEW_TYPE_FORM_BP = "BP"
    const val VIEW_TYPE_FORM_TEXTLABEL = "TextLabel"
    const val VIEW_TYPE_FORM_AGE = "Age"
    const val VIEW_TYPE_FORM_CHEKBOX = "CheckBox"
    const val VIEW_TYPE_FORM_BUTTON = "Button"
    const val VIEW_TYPE_FORM_TAG = "TagView"
    const val VIEW_TYPE_TIME = "TimeView"
    const val VIEW_TYPE_MENTAL_HEALTH = "MentalHealthView"
    const val VIEW_TYPE_INSTRUCTION = "Instruction"
    const val VIEW_TYPE_HEIGHT = "Height"
    const val VIEW_TYPE_SCALE_INDICATOR = "ScaleIndicator"
    const val VIEW_INFORMATION_LABEL = "InformationLabel"
    const val VIEW_TYPE_DIALOG_CHECKBOX = "DialogCheckbox"
    const val VIEW_TYPE_FORM_QR = "QRView"
    const val VIEW_TYPE_SINGLE_SELECTION = "SingleSelectionView"
    const val VIEW_TYPE_NO_OF_DAYS = "NoOfDaysView"
}
