package com.medtroniclabs.spice.common

import android.provider.ContactsContract

object DefinedParams {
    const val ZERO = "0"

    const val ID = "id"
    const val male = "male"
    const val female = "female"
    const val AT_CHAR = "@"
    const val span_count_1 = 1
    const val span_count_3 = 3
    const val isMemberRegistration = "isMemberRegistration"
    const val MemberID = "memberID"
    const val MenuId = "MenuId"
    const val NAME = "name"
    const val id = "id"
    const val ICCM = "ICCM"
    const val TB = "TB"
    const val No = "No"
    const val Yes = "Yes"
    const val HasSleptUnusually = "has_slept_usually"
    const val HasConvulsions = "has_convulsions"
    const val HasVomitEverything = "has_vomiting_everything"
    const val IsUnableToDrink = "is_unable_to_drink_or_breastfeed"
    const val MUAC = "muac"
    const val HasCough = "has_cough"
    const val HasFever = "has_fever"
    const val HasDiarrhoea = "has_diarrhoea"
    const val NoOfBreaths= "no_of_breaths_per_minute"
    const val IsAmoxicillinDispensed = "is_amoxicillin_dispensed"
    const val IsACTDispensed = "is_act_dispensed"
    const val IsORSDispensed = "is_ors_dispensed"
    const val IsZincDispensed = "is_zinc_dispensed"
    const val Dispensed = "Dispensed"
    const val Amoxicillin = "Amoxicillin"
    const val ACT = "ACT"
    const val ORS = "ORS"
    const val Zinc = "Zinc"
    const val RDTTestResult = "rdt_test_result"
    const val DiarrhoeaSigns= "diarrhoeaSigns"
    const val AssessmentNotes = "assessmentNotes"
    const val NextFollowupDate = "nextFollowupDate"
    const val PHUSite1 = "PHU Site 1"
    const val PHUSite2 = "PHU Site 2"
    const val PHUSite3 = "PHU Site 3"
    const val ReferredPHUSite = "referredPHUSite"
    const val Positive = "+Ve"
    const val HasNightSweats = "has_night_sweats"
    const val CoughTBSummary = "Cough (>2 Weeks)"
    const val DrenchingNightSweats = "Drenching Night Sweats"
    const val DefaultID = "-1"
    const val Summary = "summary"
    const val Other = "Other"
    const val ENABLED = "enabled"
    const val Username = "username"
    const val Password = "password"
    const val Authorization = "Authorization"
    const val ACTION_SESSION_EXPIRED =
        "${ContactsContract.Directory.PACKAGE_NAME}.action.SL_SESSION_EXPIRED"
    const val SL_SESSION = "sl_session"
    const val HOUSEHOLD_MEMBER_REGISTRATION = "household_member_registration"
    const val DefaultSelectID = -1L
    const val DefaultIDLabel = "--Select--"
}