package com.medtroniclabs.spice.common

object RoleConstant {
    val PROVIDER = "PROVIDER"
    val COMMUNITY_HEALTH_WORKER = "CHW"
    val PEER_SUPERVISOR = "PEER_SUPERVISOR"
    val SECHN = "SECHN"
    val MCHA = "MCHA"
    val CHA = "CHA"
    val MID_WIFE = "MID_WIFE"
    val LAB_ASSISTANT = "LAB_ASSISTANT"
    val SRN = "SRN"
    val COMMUNITY_HEALTH_PROVIDER = "CHP"
    val NUTRITIONIST = "NUTRITIONIST"
    val PHYSICIAN_PRESCRIBER = "PHYSICIAN_PRESCRIBER"
    val COUNSELOR = "COUNSELOR"
    val PHARMACIST = "PHARMACIST"
    val NURSE = "NURSE"
    val HRIO = "HRIO"
    val LAB_TECHNICIAN = "LAB_TECHNICIAN"
    val HEALTH_SCREENER = "HEALTH_SCREENER"
    val COMMUNITY_HEALTH_PROMOTER = "COMMUNITY_HEALTH_PROMOTER"
}